#광석을 캣을때 바로 광물로 변환할지 설정
direct-ore: true

#광석 목록 및 확률(모든 광물의 확률을 더할시 100%가 되어야 합니다.)
#아이템코드:확률
ore-list:
 1: 50
 16: 18
 15: 10
 14: 8
 21: 6
 73: 5
 56: 2
 129: 1

#광산의 높이 
mine-height: 1
#광물이 재생성되는데 걸리는 ms
#1ms = 0.001초
mine-reset-milisec: 500